const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../assets/js/core.js'),X=require('../assets/js/sheets.js');
const {makeHarness,Storage}=require('./dom-harness.cjs');
const KEY='tracklyMidnightCleanV2',OWNER='tracklyCloudSyncedUser',BASE='trackersCloudBaseAtV2',DIRTY='trackersCloudDirtyV2';
const seed=()=>({sites:[{id:'s1',siteName:'SITE DEMO',siteId:'SITE-001',projectId:'P-001',clientSiteId:'C-001',client:'Client Uji',tenant:'Tenant Uji',region:'Jawa Tengah',workType:'COLLOCATION',status:'In Progress',spmkDate:'2026-09-01',towerHeight:42,pln:{},oneflux:[],bast:[],finance:{rows:[]}},{id:'s2',siteName:'SITE DEMO',siteId:'SITE-002',projectId:'P-002',client:'Client Uji',tenant:'Tenant Uji',region:'Jawa Timur',workType:'CME',status:'Completed',spmkDate:'2026-09-10',pln:{},oneflux:[],bast:[],finance:{rows:[]}}],clients:[{id:'c1',name:'Client Uji'}],tenants:['Tenant Uji'],rules:[],pinned:[],activities:[],notes:[],bastProcesses:[],theme:'light'});
const load=async(extra={},opts={})=>{const h=makeHarness({[KEY]:JSON.stringify(seed()),...extra},opts);await h.flush();return h;};
const state=h=>h.run('state');
const submit=(h,id)=>h.el(id).onsubmit({currentTarget:h.el(id),preventDefault(){}});
const input=(e,value)=>{e.value=value;e.dispatchEvent({type:'input'});};

test('calendar dates reject impossible days and preserve local date-only values',()=>{assert.equal(C.date('2026-2-28'),'2026-02-28');assert.equal(C.date('31/02/2026'),'');assert.equal(C.date('29/02/2024'),'2024-02-29');assert.equal(C.date('2026-09-20T00:00:00Z'),'2026-09-20');});
test('rupiah parser handles grouped, decimal and invalid/negative amounts',()=>{for(const [v,n]of [[1250.5,1251],['1.250.000',1250000],['Rp 1.250,50',1251],['1250.5',1251],['-10',0],['garbage',0]])assert.equal(C.money(v),n);});
test('CSV supports quoted multiline cells and semicolon separator',()=>{assert.deepEqual(C.csvParse('SITE NAME;ALAMAT\r\n"Site; A";"Jalan\nBaru"'),[{'SITE NAME':'Site; A',ALAMAT:'Jalan\nBaru'}]);assert.throws(()=>C.csvParse('A\n"bad'));});
test('CSV export neutralizes spreadsheet formula strings',()=>{assert.match(C.csvWrite([['=1+1','@A',123]]),/"'=1\+1","'@A",123|"'=1\+1","'@A","123"/);});
test('BAST does not mark an empty BOQ complete',()=>{assert.equal(C.bastProgress({}).done,0);assert.equal(C.bastProgress({bautProcess:'Done'}).stages[2].state,'Belum lengkap');});
test('BAST undo clears the selected stage and all later stages',()=>{const r=C.stages.map(label=>({label,done:true}));C.toggleBast(r,2);assert.deepEqual(r.map(x=>x.done),[true,true,false,false,false,false]);C.toggleBast(r,5);assert.equal(r[5].done,false);});
test('PKBON matches stable site identity and avoids same-name projects',()=>{const ss=seed().sites;assert.equal(C.belongs({site:'SITE DEMO',projectId:'P-002'},ss[0],ss),false);assert.equal(C.belongs({site:'Old name',workspaceSiteId:'s1'},ss[0],ss),true);assert.equal(C.belongs({site:'SITE DEMO'},ss[0],ss),false);});
test('fractional volumes contribute to the correct total',()=>assert.equal(C.total([{vol:1.5,harga:1250},{vol:-2,harga:500}]),1875));
test('invalid backup is rejected before any write',()=>{assert.throws(()=>C.validateSnapshot({trackly:{sites:[{id:'a'}]}}));assert.throws(()=>C.validateSnapshot({trackly:{sites:[]},pkbon:{unknown:[]}}));assert.throws(()=>C.validateSnapshot({trackly:{sites:[{id:'a',siteName:'A'},{id:'a',siteName:'B'}]}}));});
test('batch storage failure rolls back earlier writes',()=>{const s=new Storage({a:'old',b:'old'});s.failKey='b';assert.throws(()=>C.writeBatch(s,[['a','new'],['b','new']]));assert.equal(s.getItem('a'),'old');assert.equal(s.getItem('b'),'old');});
test('XLSX output is a real ZIP with inline text, numeric cells and no formulas',async()=>{const z=X.workbook([['NAME','VALUE'],['=1+1',123],['Text & <xml>',42]],'Projects');const files=await X.unzip(z.buffer);assert.match(files['xl/worksheets/sheet1.xml'],/t="inlineStr"/);assert.match(files['xl/worksheets/sheet1.xml'],/<v>123<\/v>/);assert.doesNotMatch(files['xl/worksheets/sheet1.xml'],/<f>/);assert.match(files['xl/worksheets/sheet1.xml'],/Text &amp; &lt;xml&gt;/);});
test('empty startup wires every view without JS initialization errors',async()=>{const h=makeHarness();await h.flush();for(const view of ['dashboard','sites','reporting','bastprocess','pkbon','notes','settings']){h.run(`route('${view}')`);assert.equal(h.el(view+'View').classList.contains('active'),true);}assert.equal(h.el('cloudAuthGate').classList.contains('show'),true);});
test('site filter searches Project ID and global search includes archives',async()=>{const h=await load();input(h.el('siteSearch'),'P-002');assert.equal(h.el('siteRows').children.length,1);assert.equal(h.el('siteRows').children[0].dataset.open,'s2');state(h).sites[1].archived=true;input(h.el('globalAppSearch'),'P-002');h.el('globalAppSearch').dispatchEvent({type:'keydown',key:'Enter',preventDefault(){}});assert.equal(h.el('projectArchiveFilter').value,'all');assert.equal(h.el('siteRows').children.length,1);});
test('site archive is reversible and excluded from active dashboard/report',async()=>{const h=await load();h.run("openDetail('s1')");h.fire('archiveSite');assert.equal(h.el('mTotal').textContent,'1');assert.equal(state(h).sites[0].archived,true);assert.equal(h.run('reportBaseSites().length'),1);h.fire('archiveSite');assert.equal(h.el('mTotal').textContent,'2');});
test('new client and tenant can be created inside site form without closing it',async()=>{const h=await load();h.run('openSiteModal()');h.fire('quickAddClient');h.el('clientForm').elements.namedItem('name').value='New Client';submit(h,'clientForm');assert.equal(h.el('siteModal').classList.contains('open'),true);assert.equal(h.el('clientSelect').value,'New Client');h.fire('quickAddTenant');h.el('tenantForm').elements.namedItem('name').value='New Tenant';submit(h,'tenantForm');assert.equal(h.el('tenantSelect').value,'New Tenant');});
test('site edits retain archive/tasks/finance and prevent duplicate identities',async()=>{const h=await load();state(h).sites[0].archived=true;state(h).sites[0].tasks=[{id:'t',title:'Survey',status:'Completed'}];h.run("openSiteModal('s1')");h.el('siteForm').siteName.value='RENAMED';submit(h,'siteForm');assert.equal(state(h).sites[0].archived,true);assert.equal(state(h).sites[0].tasks.length,1);assert.equal(state(h).sites[0].siteName,'RENAMED');h.run('openSiteModal()');const f=h.el('siteForm');for(const [k,v]of Object.entries({client:'Client Uji',tenant:'Tenant Uji',projectId:'P-001',siteId:'SITE-001',siteName:'Duplicate'}))f.elements.namedItem(k).value=v;h.el('siteRegionPreset').value='Jawa Tengah';h.el('siteWorkPreset').value='COLLOCATION';submit(h,'siteForm');assert.equal(state(h).sites.length,2);});
test('work task add, status, save and reload update actual progress',async()=>{const h=await load();h.run("openDetail('s1')");h.fire('manageTasks');input(h.el('newTaskTitle'),'Survey');h.fire('addTask');const status=h.el('taskEditor').querySelector('[data-task-status]');status.value='Completed';status.dispatchEvent({type:'change'});h.fire('saveTasks');assert.equal(h.el('dProgressPct').textContent,'100%');assert.equal(h.el('dWorkDone').textContent,'1');assert.equal(JSON.parse(h.context.localStorage.getItem(KEY)).sites[0].tasks[0].title,'Survey');});
test('Oneflux supports custom SOW and persists custom checklist statuses',async()=>{const h=await load();h.run("openDetail('s2');openOneflux()");input(h.el('newChecklistTitle'),'Dokumen site');h.fire('addChecklistItem');const st=h.el('onefluxList').querySelector('[data-ofstatus]');st.value='OK';st.dispatchEvent({type:'change'});h.fire('saveOneflux');assert.equal(state(h).sites[1].oneflux[0].status,'OK');h.run('openOneflux()');assert.equal(h.el('onefluxPct').textContent,'100% Completed');});
test('manual BAST can be completed then rolled back in the UI handler',async()=>{const h=await load();h.run("openDetail('s1');openBast()");h.el('bastList').querySelector('[data-bi="0"]').click();h.el('bastList').querySelector('[data-bi="1"]').click();h.el('bastList').querySelector('[data-bi="0"]').click();h.fire('saveBast');assert.equal(state(h).sites[0].bast.filter(x=>x.done).length,0);});
test('BAST process completion validates content and refreshes detail without reopening',async()=>{const h=await load();h.run("openDetail('s1');openBastProcessModal()");const f=h.el('bastProcessForm');f.siteSearch.value=h.run("bastProcessSiteLabel(site('s1'))");f.taskId.value='TASK-1';f.bautProcess.value='Done';submit(h,'bastProcessForm');assert.equal(state(h).bastProcesses.length,0);f.bautInput.value='BAUT-1';f.boqLink.value='https://example.invalid/boq';submit(h,'bastProcessForm');assert.equal(state(h).bastProcesses.length,1);assert.equal(h.el('dTaskId').textContent,'TASK-1');assert.equal(state(h).sites[0].bast[0].done,true);});
test('finance preserves old SOW rows and does not lose focus on typing an addwork name',async()=>{const h=await load();state(h).sites[0].finance.rows=[{id:'old',section:'SITAC',type:'main',clientPrice:1000,payments:[{id:'p',amount:200,date:'2026-09-01'}]}];h.run("openDetail('s1');openFinance();addFinanceAddwork(financeSectionsForSite(site('s1'))[0])");const inp=h.el('financeSections').querySelector('[data-fin-label]');input(inp,'Dokumen tambahan');assert.equal(h.el('financeSections').querySelector('[data-fin-label]'),inp);h.fire('saveFinance');assert.ok(state(h).sites[0].finance.rows.some(x=>x.id==='old'));});
test('payment history totals and project cashflow remain consistent',async()=>{const h=await load({'pkbon_history':JSON.stringify([{id:'paid',workspaceSiteId:'s1',status:'Terbayar',total:400,site:'SITE DEMO',projectId:'P-001',items:[],tanggal:'2026-09-01'}])});state(h).sites[0].finance.rows=[{id:'row',section:'CME',type:'main',clientPrice:1000,payments:[{id:'p',amount:700,date:'2026-09-01'}]}];const m=h.run("financeProjectMetrics(site('s1'),site('s1').finance.rows)");assert.equal(m.client,1000);assert.equal(m.expense,400);assert.equal(m.receivable,300);assert.equal(m.profit,600);assert.equal(m.cashflow,300);});
test('notes create/edit/pin/archive/restore/delete persists across module navigation',async()=>{const h=await load();h.run('openNoteModal()');input(h.el('noteTitle'),'Todo');input(h.el('noteBody'),'Uji catatan');submit(h,'noteForm');const id=state(h).notes[0].id;h.run(`toggleNotePin('${id}');toggleNoteArchive('${id}')`);assert.equal(state(h).notes[0].archived,true);assert.equal(state(h).notes[0].pinned,false);h.run(`toggleNoteArchive('${id}');openNoteModal('${id}')`);input(h.el('noteBody'),'Sudah diedit');submit(h,'noteForm');assert.equal(state(h).notes[0].body,'Sudah diedit');h.run(`deleteNote('${id}')`);assert.equal(state(h).notes.length,0);});
test('import updates identity without removing modules and skips invalid dates',async()=>{const h=await load();const data={'SITE NAME':'Updated','PROJECT ID':'P-001','SITE ID':'SITE-001',CLIENT:'Client Uji',TENANT:'Tenant Uji',REGIONAL:'Jawa Tengah',SOW:'COLLOCATION','TANGGAL SPMK':'20/09/2026'};h.context.rows=[data,{...data,'SITE ID':'BAD','TANGGAL SPMK':'31/02/2026'}];h.run('importSiteRows(rows)');assert.equal(state(h).sites.length,2);assert.equal(state(h).sites[0].siteName,'Updated');assert.equal(h.el('importUpdateCount').textContent,'1');assert.equal(h.el('importSkipCount').textContent,'1');});
test('PKBON history open handler survives rendering Projects (regression)',async()=>{const h=await load({'pkbon_history':JSON.stringify([{id:'doc1',pkbonNo:'00001-3/IX/2026',tanggal:'2026-09-20',site:'SITE DEMO',projectId:'P-001',status:'Draft',items:[],total:0}])});h.run('renderSites()');h.el('historyList').querySelector('[data-open]').click();assert.equal(h.el('pkbonNo').value,'00001-3/IX/2026');assert.equal(h.el('formTab').classList.contains('active'),true);});
test('PKBON create/save, stable site link, fractional volume, duplicate and status change',async()=>{const h=await load();h.run("openDetail('s1');newPkbonFromSite()");await h.flush();input(h.el('mBankNama'),'Penerima Uji');input(h.el('mBankRek'),'000123');input(h.el('mBank'),'Bank Uji');h.fire('addBank');h.el('bankSelect').value='0';h.el('bankSelect').dispatchEvent({type:'change'});input(h.el('pekerjaan'),'CME');const item=h.el('itemRows').children[0];input(item.querySelector('[data-k="uraian"]'),'Pekerjaan CME');input(item.querySelector('[data-k="vol"]'),'1.5');input(item.querySelector('[data-k="harga"]'),'1.250');h.fire('btnSave');await h.flush();let hist=JSON.parse(h.context.localStorage.getItem('pkbon_history'));assert.equal(hist.length,1);assert.equal(hist[0].workspaceSiteId,'s1');assert.equal(hist[0].total,1875);h.el('historyList').querySelector('[data-history-status]').value='Terbayar';h.el('historyList').querySelector('[data-history-status]').dispatchEvent({type:'change'});await h.flush();assert.equal(h.run("pkbonSiteStats(site('s1')).paid"),1875);h.el('historyList').querySelector('[data-dup]').click();assert.equal(h.el('status').value,'Draft');assert.notEqual(h.el('pkbonNo').value,hist[0].pkbonNo);});
test('PKBON print preview includes every detail row beyond 16',async()=>{const h=await load();for(let i=0;i<19;i++)h.fire('btnAddRow');assert.equal(h.el('itemRows').children.length,20);assert.equal(h.el('pvRows').children.length,20);});
test('master PKBON changes mark workspace dirty for cloud sync',async()=>{const h=await load();h.context.localStorage.removeItem(DIRTY);input(h.el('mBankNama'),'Uji');input(h.el('mBankRek'),'123');input(h.el('mBank'),'Bank');h.fire('addBank');await h.flush();assert.equal(h.context.localStorage.getItem(DIRTY),'1');});
test('quota errors stop success messages and retain previously saved state',async()=>{const h=await load();const old=h.context.localStorage.getItem(KEY);h.context.localStorage.failKey=KEY;assert.throws(()=>h.run('state.notes.push({id:"bad",title:"Unsaved"});save()'));assert.equal(h.context.localStorage.getItem(KEY),old);assert.match(h.el('toast').textContent,/belum tersimpan/);});
test('another tab changing data blocks stale writes',async()=>{const h=await load();h.context.dispatchEvent({type:'storage',key:KEY});assert.throws(()=>h.run('save()'),/STALE/);assert.equal(h.el('storageWarning').hidden,false);});
test('cloud first upload uses guarded RPC and marks the base version',async()=>{const h=await load({}, {session:{user:{id:'u1',email:'test@example.invalid'}}});await h.flush();assert.ok(h.requests.some(x=>x.name==='trackers_save_state'));assert.equal(h.context.localStorage.getItem(OWNER),'u1');assert.ok(h.context.localStorage.getItem(BASE));});
test('disabled account cannot access workspace or upload snapshots',async()=>{const h=await load({}, {session:{user:{id:'u1'}},access:false});assert.equal(h.requests.length,0);assert.equal(h.el('cloudAuthGate').classList.contains('show'),true);assert.equal(h.el('accessDeniedModal').classList.contains('open'),true);});
test('cloud read failure never triggers a blind overwrite',async()=>{const h=await load({}, {session:{user:{id:'u1'}},readError:true});assert.equal(h.requests.length,0);assert.equal(h.run('cloudReady'),false);});
test('cloud conflict blocks autosync until user selects a source',async()=>{const snapshot={trackly:seed(),pkbon:{}};const h=await load({[OWNER]:'u1',[BASE]:'old',[DIRTY]:'1'},{session:{user:{id:'u1'}},cloudRow:{snapshot,updated_at:'new'}});assert.equal(h.run('cloudConflict'),true);assert.equal(h.el('cloudConflictModal').classList.contains('open'),true);await h.run('cloudPush()');assert.equal(h.requests.length,0);});
test('switching accounts isolates old account data instead of uploading it',async()=>{const h=await load({[OWNER]:'u1',[BASE]:'old'},{session:{user:{id:'u2'}}});assert.equal(h.requests.length,0);assert.ok(h.context.localStorage.getItem('trackersAccount:u1'));assert.equal(JSON.parse(h.context.localStorage.getItem(KEY)).sites.length,0);assert.equal(h.context.reloaded,true);});
test('cloud errors retain unsynced local edits and explain required migration',async()=>{const h=await load({[DIRTY]:'1'},{session:{user:{id:'u1'}},rpcError:'Could not find trackers_save_state'});assert.equal(h.context.localStorage.getItem(DIRTY),'1');assert.match(h.el('cloudSyncTime').textContent,/003_sync_safety/);});

test('nested invalid backup is rejected before replacing workspace storage',async()=>{const h=await load();const old=h.context.localStorage.getItem(KEY);h.context.bad={trackly:{sites:[{id:'s1',siteName:'A',finance:{rows:[null]}}]},pkbon:{pkbon_history:[null]}};assert.throws(()=>h.run('cloudApplySnapshot(bad)'));assert.equal(h.context.localStorage.getItem(KEY),old);assert.throws(()=>C.validateSnapshot({trackly:{sites:[]},pkbon:{pkbon_templates:[null]}}));});
test('corrupt saved data starts safely and cannot overwrite local or cloud records',async()=>{const h=await load({[KEY]:'{corrupt','pkbon_history':'[null]'},{session:{user:{id:'u1'}}});assert.equal(h.requests.length,0);assert.throws(()=>h.run('save()'),/CORRUPT/);assert.equal(h.context.localStorage.getItem(KEY),'{corrupt');assert.equal(h.context.localStorage.getItem('pkbon_history'),'[null]');assert.equal(h.el('storageWarning').hidden,false);});
test('legacy PKBON association survives editing the site name',async()=>{const h=await load({pkbon_history:JSON.stringify([{id:'legacy',pkbonNo:'1',site:'SITE DEMO',projectId:'P-001',status:'Terbayar',items:[],total:2500}])});h.run("openSiteModal('s1')");h.el('siteForm').siteName.value='NAMA BARU';submit(h,'siteForm');await h.flush();assert.equal(JSON.parse(h.context.localStorage.getItem('pkbon_history'))[0].workspaceSiteId,'s1');assert.equal(h.run("pkbonSiteStats(site('s1')).paid"),2500);});
test('legacy PKBON avoids double counting for identical project/name with different SOW',()=>{const a={id:'a',projectId:'P',siteName:'SITE',workType:'CME'},b={...a,id:'b',workType:'SITAC'};assert.equal(C.belongs({projectId:'P',site:'SITE'},a,[a,b]),false);assert.equal(C.belongs({workspaceSiteId:'a'},a,[a,b]),true);});
test('quick PKBON status change cannot approve an incomplete draft',async()=>{const h=await load({pkbon_history:JSON.stringify([{id:'draft',pkbonNo:'1',site:'SITE DEMO',projectId:'P-001',status:'Draft',items:[],total:0}])});const select=h.el('historyList').querySelector('[data-history-status]');select.value='Terbayar';select.dispatchEvent({type:'change'});assert.equal(JSON.parse(h.context.localStorage.getItem('pkbon_history'))[0].status,'Draft');assert.match(h.alerts.at(-1),/lengkapi/);});
test('edits made while an upload is in flight remain pending for the next upload',async()=>{const h=await load({}, {session:{user:{id:'u1'}}});let finish;h.client.rpc=()=>new Promise(resolve=>{finish=resolve});h.run('cloudLocalTouch()');const request=h.run('cloudPush()');h.run('state.notes.push({id:"during",title:"During upload"});save()');finish({data:{ok:true,updated_at:'new-base'}});assert.equal(await request,true);assert.equal(h.context.localStorage.getItem(DIRTY),'1');assert.equal(JSON.parse(h.context.localStorage.getItem(KEY)).notes[0].title,'During upload');});
test('compressed XLSX from openpyxl handles blank columns, text IDs and 1904 dates',async()=>{const h=await load(),buf=fs.readFileSync(path.join(__dirname,'fixtures/site-import-1904.xlsx'));h.context.xlsxBytes=buf.buffer.slice(buf.byteOffset,buf.byteOffset+buf.byteLength);const rows=await h.run('TrackersSheets.readXlsx(xlsxBytes)');assert.equal(rows[0]['SITE NAME'],'SITE & UJI');assert.equal(rows[0]['PROJECT ID'],'0012');h.context.rows=rows;h.run('importSiteRows(rows)');assert.equal(state(h).sites.find(s=>s.siteId==='S-001').spmkDate,'2026-09-20');});
test('generated XLSX round trips and rejects damaged content',async()=>{const h=await load();const bytes=X.workbook([['NAME','VALUE'],['=1+1',123]]);h.context.xlsxBytes=bytes.buffer;const rows=await h.run('TrackersSheets.readXlsx(xlsxBytes)');assert.equal(rows[0].NAME,'=1+1');assert.equal(rows[0].VALUE,123);const corrupted=bytes.slice(),at=Buffer.from(corrupted).indexOf(Buffer.from('=1+1'));corrupted[at]=65;await assert.rejects(X.unzip(corrupted.buffer),/checksum/);});

test('PKBON site picker distinguishes same-name projects and saves the chosen link',async()=>{const h=await load();h.run('route("pkbon")');h.fire('btnNew');const label=h.el('siteOptions').options.find(o=>o.value.includes('P-002')).value;input(h.el('siteInput'),label);h.el('siteInput').dispatchEvent({type:'change'});assert.equal(h.el('siteInput').value,'SITE DEMO');assert.equal(h.el('projectId').value,'P-002');h.fire('btnSave');assert.equal(JSON.parse(h.context.localStorage.getItem('pkbon_history'))[0].workspaceSiteId,'s2');});
test('quota rollback restores original data even when intermediate old values are larger',()=>{class LimitedStorage extends Storage{setItem(k,v){const map=new Map(this.map);map.set(k,v);if([...map.values()].reduce((n,x)=>n+x.length,0)>6)throw new Error('Quota');super.setItem(k,v);}}const s=new LimitedStorage({a:'aaaa',b:'b'});assert.throws(()=>C.writeBatch(s,[['a','a'],['b','bbbb'],['c','ccc']]));assert.equal(s.getItem('a'),'aaaa');assert.equal(s.getItem('b'),'b');assert.equal(s.getItem('c'),null);});
test('workspace save commits the dirty marker and data together',async()=>{const h=await load();const old=h.context.localStorage.getItem(KEY);h.context.localStorage.failKey=DIRTY;assert.throws(()=>h.run('state.notes.push({id:"t",title:"Must not half-save"});save()'));assert.equal(h.context.localStorage.getItem(KEY),old);});

test('PKBON price accepts consecutive typing through trillions without resetting at thousands',async()=>{
 const h=await load(),price=h.el('itemRows').querySelector('[data-k="harga"]');
 for(const digit of '1234567890123')input(price,price.value+digit);
 assert.equal(price.value,'1.234.567.890.123');
 assert.match(h.el('grandTotalLabel').textContent,/1\.234\.567\.890\.123/);
 input(price,'Rp 250.000.000');assert.equal(price.value,'250.000.000');
 input(price,'9.3333');assert.equal(price.value,'93.333');
 input(price,'');assert.equal(price.value,'');assert.match(h.el('grandTotalLabel').textContent,/Rp 0/);
});
test('PKBON price keeps the caret next to the edited digit when regrouping',async()=>{
 const h=await load(),price=h.el('itemRows').querySelector('[data-k="harga"]');
 price.setSelectionRange=(start,end)=>{price.selectionStart=start;price.selectionEnd=end;};
 price.selectionStart=3;input(price,'129.345.678');
 assert.equal(price.value,'129.345.678');assert.equal(price.selectionStart,3);
 price.selectionStart=2;input(price,'12.45.678');
 assert.equal(price.value,'1.245.678');assert.equal(price.selectionStart,3);
});

test('task date supports add, edit, cancel, reload and clearing without changing progress',async()=>{
 const h=await load();h.run("openDetail('s1')");h.fire('manageTasks');input(h.el('newTaskTitle'),'Survey');input(h.el('newTaskDate'),'2026-09-21');h.fire('addTask');h.fire('saveTasks');
 assert.equal(state(h).sites[0].tasks[0].date,'2026-09-21');assert.match(h.el('dTaskPreview').textContent,/21/);assert.equal(h.el('dProgressPct').textContent,'0%');
 const restored=await load({[KEY]:h.context.localStorage.getItem(KEY)});assert.equal(state(restored).sites[0].tasks[0].date,'2026-09-21');
 h.fire('manageTasks');input(h.el('taskEditor').querySelector('[data-task-date]'),'2026-10-01');h.run("closeModal('tasksModal')");h.fire('manageTasks');assert.equal(h.el('taskEditor').querySelector('[data-task-date]').value,'2026-09-21');
 input(h.el('taskEditor').querySelector('[data-task-date]'),'2026-10-01');h.fire('saveTasks');assert.equal(state(h).sites[0].tasks[0].date,'2026-10-01');
 h.fire('manageTasks');input(h.el('taskEditor').querySelector('[data-task-date]'),'');h.fire('saveTasks');assert.equal(state(h).sites[0].tasks[0].date,'');
});
test('legacy tasks without dates remain editable and invalid dates cannot replace saved work',async()=>{
 const h=await load();state(h).sites[0].tasks=[{id:'old',title:'Lama',status:'Completed'}];h.run("openDetail('s1')");h.fire('manageTasks');assert.equal(h.el('taskEditor').querySelector('[data-task-date]').value,'');
 input(h.el('taskEditor').querySelector('[data-task-date]'),'2026-02-31');h.fire('saveTasks');assert.equal(state(h).sites[0].tasks[0].date,undefined);assert.match(h.el('toast').textContent,/Tanggal pekerjaan tidak valid/);
 input(h.el('taskEditor').querySelector('[data-task-date]'),'2026-09-21');h.fire('saveTasks');assert.equal(h.el('dProgressPct').textContent,'100%');
});
